"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import PageHeader from "@/components/PageHeader";
import { ChevronDown, Scale, Users, FileText, Calendar, Flag, Shield, Gavel } from "lucide-react";
import api from "@/lib/api";

interface Article { id: string; chapter: string; title: string; articles: { num: string; title: string; content?: string }[] }
interface Content { header: { label: string; title: string; titleAccent: string; description: string; breadcrumbs: { label: string }[] }; adArticles: Article[] }
const keyPoints = [
  { icon: Flag, label: "Asas", value: "Pancasila & UUD 1945", color: "#E8231A" }, { icon: Calendar, label: "Didirikan", value: "28 Oktober 2018", color: "#3B82F6" }, { icon: Users, label: "Keanggotaan", value: "Pelajar Indonesia di Auckland", color: "#10B981" }, { icon: Scale, label: "Hierarki", value: "AD-ART → Kongres → Ketua Umum", color: "#8B5CF6" }, { icon: Gavel, label: "Kuorum", value: "80% Perwakilan", color: "#F59E0B" }, { icon: Shield, label: "Pengganti", value: "2/3 Suara", color: "#06B6D4" },
];
function ArticleAccordion({ article }: { article: Article }) { const [open, setOpen] = useState(false); return <div className="border border-[#E2E8F0] rounded-xl overflow-hidden mb-4"><button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-[#F8FAFC] bg-white"><div className="flex items-center gap-4"><span className="w-12 h-12 rounded-xl bg-[#E8231A] flex items-center justify-center"><span className="text-white font-black text-xs">{article.chapter}</span></span><div><h3 className="font-bold text-[#1A2B4A]">{article.title}</h3><p className="text-xs text-[#64748B] mt-1">{article.articles.length} articles</p></div></div><ChevronDown size={20} className={`text-[#94A3B8] transition-transform ${open ? "rotate-180" : ""}`} /></button><AnimatePresence>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="px-6 pb-6 pt-2 space-y-4">{article.articles.map((item) => <div key={item.num}><h4 className="font-semibold text-[#1A2B4A]">{item.num} — {item.title}</h4>{item.content && <p className="text-[#64748B] text-sm leading-relaxed mt-1">{item.content}</p>}</div>)}</div></motion.div>}</AnimatePresence></div>; }
export default function AdArtPage() { const [content, setContent] = useState<Content | null>(null); useEffect(() => { api.getPageBySlug("about/ad-art").then((res) => { const value = res?.page?.content as Content | undefined; if (value?.header && Array.isArray(value.adArticles)) setContent(value); }).catch(() => undefined); }, []); if (!content) return null; return <><PageHeader {...content.header} /><section className="py-16 bg-[#0D1B33]"><div className="max-w-7xl mx-auto px-6"><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">{keyPoints.map((kp) => <div key={kp.label} className="bg-white/5 border border-white/10 rounded-2xl p-5 text-center"><kp.icon size={20} style={{ color: kp.color }} /><p className="text-slate-400 text-xs mt-2">{kp.label}</p><p className="text-white font-semibold text-sm">{kp.value}</p></div>)}</div></div></section><section className="py-20"><div className="max-w-4xl mx-auto px-6">{content.adArticles.map((article) => <ArticleAccordion key={article.id} article={article} />)}</div></section></>; }
